knp_snappy:
    pdf:
        enabled: true
        binary: '%env(WKHTMLTOPDF_PATH)%'
        options:
            page-size: A4
            margin-top: 10
            margin-bottom: 10
            margin-left: 10
            margin-right: 10
    image:
        enabled: false
