<?php

namespace App\Entity;

use App\Repository\ListingImageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ListingImageRepository::class)]
#[ORM\Table(name: 'listing_images')]
class ListingImage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 500)]
    private ?string $imagePath = null;

    #[ORM\Column(options: ['default' => 0])]
    private int $displayOrder = 0;

    /**
     * WebP srcset variants generated by UnidarMediaPipelineBundle.
     * Format: {'320w': '/uploads/.../img_320w.webp', '640w': '...', '1280w': '...'}
     */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $srcset = null;

    #[ORM\ManyToOne(targetEntity: Listing::class, inversedBy: 'images')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Listing $listing = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(string $imagePath): static
    {
        $this->imagePath = $imagePath;
        return $this;
    }

    public function getDisplayOrder(): int
    {
        return $this->displayOrder;
    }

    public function setDisplayOrder(int $displayOrder): static
    {
        $this->displayOrder = $displayOrder;
        return $this;
    }

    public function getListing(): ?Listing
    {
        return $this->listing;
    }

    public function setListing(?Listing $listing): static
    {
        $this->listing = $listing;
        return $this;
    }

    public function getSrcset(): ?array { return $this->srcset; }
    public function setSrcset(?array $v): static { $this->srcset = $v; return $this; }

    /**
     * Return the best srcset attribute string for use in HTML <img> tags.
     * Example: "/img_320w.webp 320w, /img_640w.webp 640w"
     */
    public function buildSrcsetAttr(): string
    {
        if (!$this->srcset) return '';
        $parts = [];
        foreach ($this->srcset as $width => $path) {
            $parts[] = $path . ' ' . $width;
        }
        return implode(', ', $parts);
    }
}
