package tn.unidar.desktop.services;

import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Base64;

public class PdfContractService {
    private static PdfContractService instance;

    private PdfContractService() {}

    public static PdfContractService getInstance() {
        if (instance == null) instance = new PdfContractService();
        return instance;
    }

    public File generateContract(JSONObject listing, JSONObject student, String studentSigBase64, String ownerSigBase64, int durationMonths, String startDate) throws Exception {
        String fileName = "Contract_" + listing.optInt("id") + "_" + System.currentTimeMillis() + ".pdf";
        File file = new File(System.getProperty("user.home"), fileName);
        
        PdfWriter writer = new PdfWriter(new FileOutputStream(file));
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf, PageSize.A4);
        document.setMargins(50, 50, 50, 50);

        // Header
        Paragraph header = new Paragraph("UNIDAR")
                .setFontSize(26)
                .setBold()
                .setFontColor(ColorConstants.BLUE)
                .setTextAlignment(TextAlignment.CENTER);
        document.add(header);

        Paragraph subHeader = new Paragraph("Student Housing Rental Contract")
                .setFontSize(14)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(30);
        document.add(subHeader);

        // Parties
        document.add(new Paragraph("BETWEEN:").setBold());
        Table partiesTable = new Table(UnitValue.createPercentArray(new float[]{1, 1})).useAllAvailableWidth();
        
        Cell ownerCell = new Cell().add(new Paragraph("LESSOR (Owner):")
                .setBold())
                .add(new Paragraph(listing.optString("owner_name", "Owner Name")))
                .add(new Paragraph("Property ID: #" + listing.optInt("id")))
                .setBorder(null);
        
        Cell studentCell = new Cell().add(new Paragraph("LESSEE (Student):")
                .setBold())
                .add(new Paragraph(student.optString("full_name", "Student Name")))
                .add(new Paragraph("Email: " + student.optString("email", "")))
                .setBorder(null);
        
        partiesTable.addCell(ownerCell);
        partiesTable.addCell(studentCell);
        document.add(partiesTable);
        document.add(new Paragraph("\n"));

        // Property Details
        document.add(new Paragraph("PROPERTY DETAILS").setBold().setFontSize(14).setFontColor(ColorConstants.DARK_GRAY));
        document.add(new Paragraph("Address: " + listing.optString("address", "N/A")));
        document.add(new Paragraph("Type: " + listing.optString("property_type", "Apartment")));
        document.add(new Paragraph("Monthly Rent: " + listing.optDouble("price", 0) + " TND"));
        document.add(new Paragraph("\n"));

        // Terms
        document.add(new Paragraph("TERMS AND CONDITIONS").setBold().setFontSize(14).setFontColor(ColorConstants.DARK_GRAY));
        document.add(new Paragraph("1. DURATION: This agreement starts on " + startDate + " for a duration of " + durationMonths + " months."));
        document.add(new Paragraph("2. PAYMENT: Rent is due on the 1st of each month."));
        document.add(new Paragraph("3. CONDUCT: The lessee agrees to respect house rules and maintain the property in good condition."));
        document.add(new Paragraph("\n\n"));

        // Signatures
        document.add(new Paragraph("SIGNATURES").setBold().setFontSize(14));
        
        Table signTable = new Table(UnitValue.createPercentArray(new float[]{1, 1})).useAllAvailableWidth();
        
        Cell ownerSign = new Cell().add(new Paragraph("Owner Signature:"));
        addSignatureToCell(ownerSign, ownerSigBase64);
        
        Cell studentSign = new Cell().add(new Paragraph("Student Signature:"));
        addSignatureToCell(studentSign, studentSigBase64);

        signTable.addCell(ownerSign);
        signTable.addCell(studentSign);
        document.add(signTable);

        // Footer
        document.add(new Paragraph("\n\nGenerated by Unidar Desktop on " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")))
                .setFontSize(8)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(ColorConstants.GRAY));

        document.close();
        return file;
    }

    private void addSignatureToCell(Cell cell, String base64) {
        if (base64 != null && base64.contains(",")) {
            try {
                String pureBase64 = base64.split(",")[1];
                byte[] bytes = Base64.getDecoder().decode(pureBase64);
                ImageData imageData = ImageDataFactory.create(bytes);
                Image img = new Image(imageData);
                img.setMaxHeight(60);
                cell.add(img);
            } catch (Exception e) {
                cell.add(new Paragraph("(Signature Error)"));
            }
        } else {
            cell.add(new Paragraph("(Awaiting Signature)").setItalic().setFontColor(ColorConstants.GRAY));
        }
        cell.setBorder(null);
    }

    public String getContractHtml(JSONObject listing, JSONObject student, int durationMonths, String startDate) {
        String title = listing.optString("title", "Property");
        String address = listing.optString("address", "N/A");
        double rent = listing.optDouble("price", 0);
        String ownerName = listing.optString("owner_name", "Owner");
        String studentName = student.optString("full_name", "Student");

        return "<!DOCTYPE html><html>" + 
               "<head><style>" +
               "body { font-family: 'Segoe UI', serif; padding: 20px; line-height: 1.6; color: #1e293b; background: white; }" +
               ".header { text-align: center; border-bottom: 2px solid #4f46e5; margin-bottom: 30px; padding-bottom: 15px; }" +
               "h1 { color: #4f46e5; margin: 0; text-transform: uppercase; letter-spacing: 1px; }" +
               ".section { margin-top: 25px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; font-weight: bold; color: #0f172a; }" +
               ".footer { margin-top: 50px; text-align: center; font-size: 0.9em; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 20px; }" +
               ".signature-box { height: 80px; border: 1px dashed #cbd5e1; margin-top: 10px; display: flex; align-items: center; justify-content: center; color: #94a3b8; font-style: italic; }" +
               "</style></head>" +
               "<body>" +
               "<div class='header'><h1>Contrat de Bail Numérique</h1><p>Généré via UNIDAR Desktop</p></div>" +
               "<div class='section'>PARTIES AU CONTRAT</div>" +
               "<p><b>Propriétaire:</b> " + ownerName + "</p>" +
               "<p><b>Locataire (Étudiant):</b> " + studentName + "</p>" +
               "<div class='section'>OBJET DU CONTRAT</div>" +
               "<p><b>Logement:</b> " + title + "</p>" +
               "<p><b>Adresse:</b> " + address + "</p>" +
               "<div class='section'>CONDITIONS DE LOCATION</div>" +
               "<p><b>Durée:</b> " + durationMonths + " mois</p>" +
               "<p><b>Date de début:</b> " + startDate + "</p>" +
               "<p><b>Loyer Mensuel:</b> " + rent + " TND</p>" +
               "<div class='section'>ENGAGEMENT</div>" +
               "<p>Le locataire s'engage à respecter le règlement intérieur et à payer le loyer mensuel dans les délais. " +
               "Ce document constitue un engagement ferme une fois signé électroniquement.</p>" +
               "<div style='margin-top: 40px; display: flex; justify-content: space-between;'>" +
               "<div><b>Signature Propriétaire:</b><div class='signature-box'>[Signé via Plateforme]</div></div>" +
               "<div><b>Signature Étudiant:</b><div class='signature-box'>[VOTRE SIGNATURE CI-DESSOUS]</div></div>" +
               "</div>" +
               "<div class='footer'>UNIDAR - Système de Gestion Locative Étudiante &copy; 2026</div>" +
               "</body></html>";
    }
}
